name: Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  trigger-tests:
    name: Trigger Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      pull-requests: write
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '!run-tests') &&
      (github.event.comment.author_association == 'OWNER' || 
       github.event.comment.author_association == 'MEMBER' || 
       github.event.comment.author_association == 'COLLABORATOR')
    
    steps:
    - name: React to comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: 'rocket'
          });
    
    - name: Trigger test workflow
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'test.yml',
            ref: 'main',
            inputs: {
              pr_number: context.issue.number.toString()
            }
          });